version: '3'

services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.production 
    volumes: 
      - /api-note/api/code:/app/api/code
    ports:
      - '8080:8080'