version: '3'

services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: 
      - C:\Users\kaito\Documents\Project\api-note\api:/usr/src/app/api
    ports:
      - '9090:9090'