version: '3'

services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.production 
    volumes: 
      - /home/kmactfweb/api-note/api:/usr/src/app/api
    ports:
      - '80:80'