  
name: Docker-note

on:
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: image

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker-compose -f docker-compose.production.yml -p note build

      - name: Push image
        run: |
          VERSION=latest

          docker tag note_api docker.pkg.github.com/kaitoryouga/api-note/note_api:$VERSION
          docker push docker.pkg.github.com/kaitoryouga/api-note/note_api:$VERSION
